services:
  - type: web
    name: salesforce-assistant-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: https://github.com/LordHenry90/salesforce-agent-frontend.git # Modifica con il tuo repository
    branch: main
    healthCheckPath: /health
    envVars:
      - key: MODEL_API_URL
        value: https://lordhenry-salesforce-agent.hf.space
      - key: N8N_WEBHOOK_URL  # Aggiungi questa riga
        sync: false           # Imposta l'URL tramite la dashboard di Render
      - key: API_KEY
    autoDeploy: true
    plan: free # Piano gratuito
